### ISSUE TITLE
Using with zplug

### ISSUE THREAD

**Issue by asymmetric** [b4b4r07/http_code#1]
Hi @b4b4r07 :)

How would I use this plugin with zplug? If I try `zplug "b4b4r07/http_code", as:command, of:bin`, I don't get the completions, as they're saved under `src/`.

Then I tried adding two entries, one with `as:command`, the other one just for the completion. But the second one ended up overriding the first.

I also tried `zplug "b4b4r07/http_code", as:command, of:"{bin,src}"` but that didn't work either, i.e. the completion wasn't loaded.

More generally, is there a specific structure a command plugin needs to follow in order to have both the bin and the completion loaded by zplug?

Thanks! :palm_tree:

**Comment by babarot** [comment]
Thank you for your report!

I see. That's for sure.

Now, zplug doesn't have any tags or methods in order to have both the bin and the completion loaded. I will add new tag (somewhat like `fpath`). How do you think about introducing this tag?

``` console
$ zplug "b4b4r07/http_code", as:command, of:bin, fpath:src
```

If completion files are in project root directory:

``` console
$ zplug "foo/bar", as:command, of:bin, fpath:.
```

**Comment by asymmetric** [comment]
I think `fpath:` might be a bit cryptic for people not familiar with zsh's internals. Maybe something like `completion:`, or maybe `compl:`?

Also, do I understand correctly that `fpath:` will look for a file named `_binaryname`? Could it happen that the completion filename is different?

**Comment by babarot** [comment]
> I think `fpath:` might be a bit cryptic for people not familiar with zsh's internals. Maybe something like `completion:`, or maybe `compl:`?

I see. Hmmmm. Okay, let me think about it please.

> Also, do I understand correctly that fpath: will look for a file named _binaryname? 

Yes!

> Could it happen that the completion filename is different?

It does not happen. However, completion file might be located the directory different from command such as `http_code`.

**Comment by babarot** [comment]
Hi, @asymmetric !

How do you think this change? https://github.com/b4b4r07/zplug/issues/34

**Comment by babarot** [comment]
All you have to do is:

``` console
$ zplug "b4b4r07/http_code", as:command
```

**Comment by asymmetric** [comment]
Works great!
